JS exercise-5 (lesson 22)
rohan-repos/comit-exercises pull request #5
Opened 2020-09-26 01:17 UTC by rohan-repos

2020-09-26 21:35 UTC, anton-shevchook commented on JS_exercises/exercise-5/index.js
> +let numTwo = prompt("Enter the second number to compare");
It's better to convert prompt values to "number" type before comparing them.

2020-09-26 21:37 UTC, anton-shevchook commented on JS_exercises/exercise-3/index.js
> +let result = prompt("Enter some number here", 20);
Good that you changed [20] to 20. 👍 
Also need to convert entered values to "number" type. Otherwise they are string and you will be comparing strings.

2020-09-26 21:39 UTC, anton-shevchook requested changes
Please add improvements mentioned in comments, test, push your changes and you can merge this pull request.

2020-09-28 23:09 UTC, rohan-repos commented on JS_exercises/exercise-3/index.js
> +let result = prompt("Enter some number here", 20);
I had converted it before but then I though that the comparison based on the UTF table will also be correct so I removed it. converted it to number now.

2020-09-28 23:09 UTC, merged